
from gym.envs.registration import register
from gym_bz_games.envs import *

register(id='BZ-Mario-v0', entry_point='gym_bz_games:Mario')
register(id='BZ-Mario-1-1-v0', entry_point='gym_bz_games:Mario11')
register(id='BZ-Mario-1-2-v0', entry_point='gym_bz_games:Mario12')
register(id='BZ-Mario-1-3-v0', entry_point='gym_bz_games:Mario13')
register(id='BZ-Mario-1-4-v0', entry_point='gym_bz_games:Mario14')
register(id='BZ-Mario-2-1-v0', entry_point='gym_bz_games:Mario21')
register(id='BZ-Mario-2-2-v0', entry_point='gym_bz_games:Mario22')
register(id='BZ-Mario-2-3-v0', entry_point='gym_bz_games:Mario23')
register(id='BZ-Mario-2-4-v0', entry_point='gym_bz_games:Mario24')
register(id='BZ-Mario-3-1-v0', entry_point='gym_bz_games:Mario31')
register(id='BZ-Mario-3-2-v0', entry_point='gym_bz_games:Mario32')
register(id='BZ-Mario-3-3-v0', entry_point='gym_bz_games:Mario33')
register(id='BZ-Mario-3-4-v0', entry_point='gym_bz_games:Mario34')
register(id='BZ-Mario-4-1-v0', entry_point='gym_bz_games:Mario41')
register(id='BZ-Mario-4-2-v0', entry_point='gym_bz_games:Mario42')
register(id='BZ-Mario-4-3-v0', entry_point='gym_bz_games:Mario43')
register(id='BZ-Mario-4-4-v0', entry_point='gym_bz_games:Mario44')
register(id='BZ-Mario-5-1-v0', entry_point='gym_bz_games:Mario51')
register(id='BZ-Mario-5-2-v0', entry_point='gym_bz_games:Mario52')
register(id='BZ-Mario-5-3-v0', entry_point='gym_bz_games:Mario53')
register(id='BZ-Mario-5-4-v0', entry_point='gym_bz_games:Mario54')
register(id='BZ-Mario-6-1-v0', entry_point='gym_bz_games:Mario61')
register(id='BZ-Mario-6-2-v0', entry_point='gym_bz_games:Mario62')
register(id='BZ-Mario-6-3-v0', entry_point='gym_bz_games:Mario63')
register(id='BZ-Mario-6-4-v0', entry_point='gym_bz_games:Mario64')
register(id='BZ-Mario-7-1-v0', entry_point='gym_bz_games:Mario71')
register(id='BZ-Mario-7-2-v0', entry_point='gym_bz_games:Mario72')
register(id='BZ-Mario-7-3-v0', entry_point='gym_bz_games:Mario73')
register(id='BZ-Mario-7-4-v0', entry_point='gym_bz_games:Mario74')
register(id='BZ-Mario-8-1-v0', entry_point='gym_bz_games:Mario81')
register(id='BZ-Mario-8-2-v0', entry_point='gym_bz_games:Mario82')
register(id='BZ-Mario-8-3-v0', entry_point='gym_bz_games:Mario83')
register(id='BZ-Mario-8-4-v0', entry_point='gym_bz_games:Mario84')

register(id='BZ-MarioRandom-v0', entry_point='gym_bz_games:MarioRandom')

register(id='BZ-Tetris-v0', entry_point='gym_bz_games:Tetris')
register(id='BZ-Tetris2-v0', entry_point='gym_bz_games:Tetris2')

