BZ-Mario-v0: &BZ-Mario-v0
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 8
  n_timesteps: !!float 1e9
  n_epochs: 20

  # train begin
  gamma: 0.9
  gae_lambda: 0.8
  learning_rate: !!float 1e-4
  n_steps: 768
  batch_size: 128
  clip_range: 0.5
  clip_range_vf: 0.5
  ent_coef: 0.0
  max_grad_norm: 0.5
  vf_coef: 0.5

  # train center 
  #gamma: 0.95
  #gae_lambda: 0.9
  #learning_rate: !!float 3e-5
  #n_steps: 1024
  #batch_size: 256
  #clip_range: 0.3
  #clip_range_vf: 0.3
  #ent_coef: 0.0
  #max_grad_norm: 0.5
  #vf_coef: 0.5


  # train end
  #gamma: 0.995
  #gae_lambda: 0.99
  #learning_rate: !!float 1e-5
  #n_steps: 1280
  #batch_size: 384
  #clip_range: 0.05
  #clip_range_vf: 0.05
  #ent_coef: 0.0
  #max_grad_norm: 0.5
  #vf_coef: 0.5


  policy_kwargs: "dict(activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"


BZ-MarioRandom-v0:
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 12
  n_timesteps: !!float 1e9
  n_epochs: 20

  # train begin
  gamma: 0.9
  gae_lambda: 0.8
  learning_rate: !!float 1e-4
  n_steps: 1024
  batch_size: 256
  clip_range: 0.5
  clip_range_vf: 0.5
  ent_coef: 0.0
  max_grad_norm: 0.5
  vf_coef: 0.5

  # train center
  #gamma: 0.95
  #gae_lambda: 0.9
  #learning_rate: !!float 3e-5
  #n_steps: 1024
  #batch_size: 256
  #clip_range: 0.3
  #clip_range_vf: 0.3
  #ent_coef: 0.0
  #max_grad_norm: 0.5
  #vf_coef: 0.5


  # train end
  #gamma: 0.995
  #gae_lambda: 0.99
  #learning_rate: !!float 1e-5
  #n_steps: 1280
  #batch_size: 384
  #clip_range: 0.05
  #clip_range_vf: 0.05
  #ent_coef: 0.0
  #max_grad_norm: 0.5
  #vf_coef: 0.5


  policy_kwargs: "dict(activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[512, 512, 1024, 512, 256], vf=[256, 512, 1024, 512, 256])]
                       )"



BZ-Tetris2-v0:
  policy: 'MlpPolicy'
  frame_stack: 4
  n_envs: 16
  n_timesteps: !!float 1e9
  batch_size: 512
  ent_coef: 1.312836252706057e-05
  clip_range: 0.1
  n_epochs: 20
  max_grad_norm: 0.5
  vf_coef: 0.5

  # train begin
  #gamma: 0.95
  #gae_lambda: 0.9
  #learning_rate: !!float 5e-5
  #n_steps: 384
  #batch_size: 384

  # train center
  #gamma: 0.98
  #gae_lambda: 0.94
  #learning_rate: !!float 2.5e-5
  #n_steps: 512
  #batch_size: 512

  # train end
  gamma: 0.995
  gae_lambda: 0.99
  learning_rate: !!float 1e-5
  n_steps: 768
  batch_size: 768


  policy_kwargs: "dict(activation_fn=nn.Tanh,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"

BZ-Tetris3-v0:
  policy: 'MlpPolicy'
  frame_stack: 4
  n_envs: 16
  n_timesteps: !!float 1e9
  batch_size: 512
  ent_coef: 1.312836252706057e-05
  clip_range: 0.1
  n_epochs: 20
  max_grad_norm: 0.5
  vf_coef: 0.5

  # train begin
  gamma: 0.95
  gae_lambda: 0.9
  learning_rate: !!float 5e-5
  n_steps: 384
  batch_size: 384

  # train center
  #gamma: 0.98
  #gae_lambda: 0.94
  #learning_rate: !!float 2.5e-5
  #n_steps: 512
  #batch_size: 512

  # train end
  #gamma: 0.995
  #gae_lambda: 0.99
  #learning_rate: !!float 1e-5
  #n_steps: 768
  #batch_size: 768


  policy_kwargs: "dict(activation_fn=nn.Tanh,
                       net_arch=[dict(pi=[256, 512, 1024, 512, 256], vf=[256, 512, 1024, 512, 256])]
                       )"



BZ-Tetris-v0:
  policy: 'MlpPolicy'
  frame_stack: 4
  n_envs: 16
  n_timesteps: !!float 1e9
  batch_size: 512
  n_steps: 512
  gamma: 0.995
  learning_rate: !!float 3.5e-5
  ent_coef: 1.312836252706057e-05
  clip_range: 0.1
  n_epochs: 20
  gae_lambda: 0.98
  max_grad_norm: 0.3
  vf_coef: 0.5868554921198178

  policy_kwargs: "dict(activation_fn=nn.Tanh,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"



BZ-Mario-1-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-4-v0:
  <<: *BZ-Mario-v0
