BZ-Mario-bak-v0: &BZ-Mario-bak-v0
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 8
  n_steps: 512
  n_epochs: 4
  batch_size: 512
  n_timesteps: !!float 1e9
  vf_coef: 0.5
  gamma: 0.99
  gae_lambda: 0.9
  ent_coef: 0.0
  sde_sample_freq: 4
  max_grad_norm: 0.5
  vf_coef: 0.5
  learning_rate: !!float 3e-5
  clip_range: 0.4
  normalize: true
  policy_kwargs: "dict(log_std_init=-2,
                       ortho_init=False,
                       activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"

BZ-Mario-v0: &BZ-Mario-v0
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 8
  n_steps: 512
  n_epochs: 4
  batch_size: 512
  n_timesteps: !!float 1e9
  clip_range: lin_0.2
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: !!float 5e-5

  policy_kwargs: "dict(log_std_init=-2,
                       ortho_init=False,
                       activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"


BZ-Tetris-v0:
  policy: 'MlpPolicy'
  frame_stack: 4
  n_envs: 16
  n_steps: 512
  n_epochs: 4
  batch_size: 512
  n_timesteps: !!float 1e8
  clip_range: lin_0.2
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: !!float 5e-5

  policy_kwargs: "dict(log_std_init=-2,
                       ortho_init=False,
                       activation_fn=nn.ReLU,
                       net_arch=[dict(pi=[256, 512, 512, 256], vf=[256, 512, 512, 256])]
                       )"







BZ-Mario-1-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-4-v0:
  <<: *BZ-Mario-v0
