BZ-Mario-v0: &BZ-Mario-v0
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 8
  n_timesteps: !!float 2e5
  policy: 'CnnPolicy'
  learning_rate: lin_1e-4
  batch_size: 128
  buffer_size: 100000
  learning_starts: 10000
  gamma: 0.995
  target_update_interval: 1
  train_freq: 256
  gradient_steps: -1
  exploration_fraction: 0.24
  exploration_final_eps: 0.18
  policy_kwargs: "dict(net_arch=[256,  512, 512, 256], n_quantiles=170)"

BZ-Tetris-v0:
  policy: 'CnnPolicy'
  frame_stack: 4
  n_envs: 16
  n_steps: 512
  n_epochs: 4
  batch_size: 512
  n_timesteps: !!float 1e9
  clip_range: lin_0.1
  vf_coef: 0.5
  ent_coef: 0.01
  learning_rate: !!float 1e-4
  gradient_steps: 8
  exploration_fraction: 0.2
  exploration_final_eps: 0.07
  optimize_memory_usage: True
  policy_kwargs: "dict(net_arch=[256, 512, 512, 256], n_quantiles=150)"



BZ-Mario-1-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-1-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-2-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-3-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-4-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-5-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-6-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-7-4-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-1-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-2-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-3-v0:
  <<: *BZ-Mario-v0

BZ-Mario-8-4-v0:
  <<: *BZ-Mario-v0
